<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>

<h2>[_CRUD_NAME_]</h2>
<div class="col-md-4">
	<a class='btn btn-primary' href='<?php echo $this->baseUrl('conexoes/insert'); ?>' title='Adicionar Novo'>
	<i class='fa fa-2x fa-plus'> </i>
	</a>
</div>
<table class='table'>
<tr>
	<th>Id</th>
	<th>Nome</th>
	<th>Host</th>
	<th>Banco</th>	
	<th>Opções</th>
<tr>
<?php
    $page = $this->_getParam('pg', 1);
    $bootstrap = $this->getInvokeArg('bootstrap');
    $lines=$bootstrap->getOptions()['aplicativo']['paginator']['lines'];
    $paginator=new Aplicacao_Paginador_Monta();
    $paginator=$paginator->constructor($this->items,$page,$lines);

 echo count($this->items)<1?
"<div class='alert alert-info alert-dismissible fade show'>Sem Registros<button type='button' class='close' data-dismiss='alert' aria-label='Close><span aria-hidden='true'>&times;</span></button></div>":
''; ?>


<?php 
if(sizeof($paginator)):
foreach ($paginator as $c=>$items): 
?>
<tr>
	<td><?php echo $items['id'] ?></td>
	<td><?php echo $items['nome'] ?></td>
	<td><?php echo $items['host'] ?></td>
	<td><?php echo $items['dbname'] ?></td>
	<td>
	<div class="col-md-4">
	<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('conexoes/view/'); ?>' title='Ver Detalhes'><input type='hidden' value=<?php echo $items['id']; ?> name='id' id='id'/><button type='submit' class='btn btn-primary'><i class='fa fa-2x fa-eye'> </i></button>

	</form>
	<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('conexoes/delete/'); ?>' title='Excluir'><input type='hidden' value=<?php echo $items['id']; ?> name='id' id='id'/><button type='submit' class='btn btn-danger'><i class='fa fa-2x fa-trash'> </i></button>

	</form>
	
</div>
</td>
</tr>
<?php endforeach; 

endif;
?>
</table>
<?php echo $this->items; ?>
