<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>

<h2>Detalhe de conexão</h2>
<div class="col-md-4">
<form style="float:left;margin-right:5px;" method='POST' ' action='<?php echo $this->baseUrl('conexoes/insert'); ?>' title='Adicionar Novo'><button type='submit' class='btn btn-primary'><i class='fa fa-2x fa-plus'> </i></button>

	</form>

	&nbsp;	

<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('conexoes/update
'); ?>' title='Alterar Dados'><input type='hidden' value=<?php echo $this->item['id']; ?> name='id' id='id'/><button type='submit' class='btn btn-primary'><i class='fa fa-2x fa-sync'> </i></button>

	</form>


</div>
<table class='table'>
<?php unset($this->item['password']);?>
<?php foreach ($this->item as $k=>$a): ?>
<tr><td><?php echo ucfirst($k) ?></td><td><?php echo $a ?></td></tr>
<?php endforeach; ?>
</table>
