<?php
         	
    	$avisos=0;
    	$user= $escola = Zend_Auth::getInstance()->getIdentity()->getSenhaAlterada();
    	$senhaAlt1=$user;
    	$url=$this->url(array('controller' => 'cadastro', 'action' => 'alterasenha', 'module' => 'default'), '', true);
    	//$url="cadastro/alterasenha";
    	if($senhaAlt1==0){
    		$avisos++;
    		$senhaAlt='<h2><span class="aviso-senha" >Sua senha deve ser alterada para sua segurança</span></h2>
    		<a href="'.$url.'"><span class="aviso-senha" >Clique aqui para fazê-lo</span></a>';}
    	else{$senhaAlt="";}
    	
    	
		$url2=$this->url(array('controller' => 'cadastro', 'action' => 'alt', 'module' => 'default'), '', true);
		
    		
    		$avisos="<div id='avisos'>".$senhaAlt."</div>";
    	
    	

?>
<style>
div{}
    a:link,
    a:visited
    {
        color: #0398CA;
    }

    span.zf-name
    {
        color: #91BE3F;
    }
    #avisos span.completo
    {
        color: #91BE3F;
        background-image: url(images/03.png);
        background-repeat: no-repeat;
        background-position:right;
    }
   span.aviso-senha
    {
        color: #FF0000;
    }

    div#welcome
    {
        color: #FFFFFF;
          background-color:#FFFFFF;
        background-image: url(images/bkg_header.jpg);
         background-repeat: repeat-x;
       /* width:  600px;*/
        height: 400px;
        border: 2px solid #444444;
        overflow: hidden;
        text-align: center;
    }

    div#more-information
    {
        background-image: url(images/bkg_body-bottom.gif);
        height: 100%;
    }
    
img.imgEsc
    {
        
        height: 50%;
    	width : auto;
    	float:left;
    	border: 1px dashed #444444;
    }
    #welcome{
	clear:both;
    }
    
</style>

<div id="welcome">
<img class="imgEsc" src="<?php echo $this->baseUrl().'/src/logo/1.jpg'; ?>"/>
  <p>&nbsp;</p>
    <div id="avisos">
    <br />
    <?php echo $avisos;  ?>
    
</div>
    <div id="more-information">
        
        <p>
            Opções mais visitadas: <br />
            <a href="<?php echo $this->baseUrl().'/notas/consulta'; ?>">Notas</a> |
            
        </p>
        
    </div>
    
    
</div>