<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>

<h2></h2>
<div class="col-md-4">
<form style="float:left;margin-right:5px;" method='GET' action='<?php echo $this->baseUrl('/insert'); ?>' title='Adicionar Novo'><button type='submit' class='btn btn-primary'><i class='fa fa-2x fa-plus'> </i></button>

	</form>

	&nbsp;	

<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('/update
'); ?>' title='Alterar Dados'><input type='hidden' value=<?php echo $this->item['']; ?> name='' id=''/><button type='submit' class='btn btn-primary'><i class='fa fa-2x fa-sync'> </i></button>

	</form>


</div>
<table class='table'>
<?php $list_names=array(''); ?>

<?php foreach ($this->item as $k=>$a): ?>
<?php if (in_array($k,$list_names)): ?>
<tr><td><?php echo ucfirst($k) ?></td><td><?php echo $a ?></td></tr>
<?php endif; ?>
<?php endforeach; ?>
</table>
