<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>

<h2>Confirma Exclusão do Registro?</h2>
<div class="col-md-4">

<form style="float:left;margin-right:5px;" method='POST' ' action='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]/delete
'); ?>' title='Excluir'><input type='hidden' value='<?php echo $this->item['[__CRUD_KEY_PARAM__]']; ?>' name='[__CRUD_KEY_PARAM__]' id='[__CRUD_KEY_PARAM__]'/><input type='hidden' value='DELETE' name='ConfirmAction' id='ConfirmAction'/><button type='submit' class='btn btn-danger'><i class='fa fa-trash'> Sim, confirmo!</i></button>

	</form>
<a class='btn btn-success' href='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]
'); ?>'><i class='fa fa-check'> Não, obrigado!</i></a>

</div>
<table class='table'>
<?php $list_names=[__LIST_NAMES_ARRAY__]; ?>

<?php foreach ($this->item as $k=>$a): ?>
<?php if (in_array($k,$list_names)): ?>
<tr><td><?php echo ucfirst($k) ?></td><td><?php echo $a ?></td></tr>
<?php endif; ?>
<?php endforeach; ?>
</table>
