<?php echo ( sizeof( $this->messages ) > 0 ) ? $this->messages[0] : ""; ?>

<h2>[__CONTROLLER_CRUD_LABEL__]</h2>
<div class="col-md-5">
	<a  style="float:left;margin-right:10px;" class='btn btn-primary' href='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]/insert'); ?>' title='Adicionar Novo'>
	<i class='fa fa-plus'> </i>
	</a>
<form style="float:left;margin-bottom:3px;" method='POST' ' action='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]'); ?>' title='Pesquisar'>
<div class='input-group btn-group'>
	<input type='text' class='form-control' name='searchWord' placeholder='busca'id='searchWord'/>
<div class='btn-group'>
	<button type='submit' name='submit' value='Search' class='btn btn-danger'>
	<i class='fa fa-search'> </i></button>

	<a class='btn btn-secondary' href='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]'); ?>' title='Limpar'>
	<i class='fa fa-eraser'> </i>
	</a>
</div>
</div>
</form>
</div>
<table class='table'>
<tr>
[__TH_LIST_FIELDS__]
<th>Opções </th>
<tr>
<?php echo count($this->items)<1?
"<br><br><div class='alert alert-info alert-dismissible fade show'>Sem Registros<button type='button' class='close' data-dismiss='alert' aria-label='Close><span aria-hidden='true'>&times;</span></button></div>":
''; ?>
<?php foreach ($this->items as $items): ?>
<tr>
[__TD_LIST_NAMES__]
	<td>
	<div class="col-md-5">
	<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]/view/'); ?>' title='Ver Detalhes'>
	<input type='hidden' value=<?php echo $items['[__CRUD_KEY_PARAM__]']; ?> name='[__CRUD_KEY_PARAM__]' id='[__CRUD_KEY_PARAM__]'/>
	<button type='submit' class='btn btn-primary'><i class='fa fa-eye'> </i></button>

	</form>
	<form style="float:left" method='POST' ' action='<?php echo $this->baseUrl('[__CONTROLLER_CRUD_NAME__]/delete/'); ?>' title='Excluir'>
	<input type='hidden' value=<?php echo $items['[__CRUD_KEY_PARAM__]']; ?> name='[__CRUD_KEY_PARAM__]' id='[__CRUD_KEY_PARAM__]'/>
	<button type='submit' class='btn btn-danger'><i class='fa fa-trash'> </i></button>
	</form>
	
</div>
</td>
</tr>
<?php endforeach; ?>
</table>
<?php echo $this->items; ?>
