<?php echo $this->doctype();
$version = Zend_Registry::get('_version');
$name = Zend_Registry::get('_appname');
	 
 ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  
  <title></title>
   <?php 
   $url=$this->baseUrl();
   $this->headLink()->offsetSetStylesheet(0,$url.'/css/fontawesome-free-5.8.1-web/css/all.min.css');
   $this->headLink()->offsetSetStylesheet(1,$url.'/css/bootstrap-4.3.1/dist/css/bootstrap.min.css');
   $this->headLink()->offsetSetStylesheet(2,$url.'/css/estilobase.css');
   $this->headScript()->offsetSetFile(0, $this->baseUrl('script/jquery-3.3.1.js' ));
   $this->headScript()->offsetSetFile(1,$this->baseUrl('css/bootstrap-4.3.1/dist/js/bootstrap.min.js' ));
   $this->headScript()->offsetSetFile(2, $this->baseUrl('script/menu.js' ));
 
 	echo  $this->headLink();

  	echo $this->headScript();
  ?>
  
	
</head>
<body>
<div id="max" class="">

<div id="bod2" class="col-md-12 border border-light">
<div id="banner" class="col-md-12 border border-dark rounded">
<div id="tit" class="">
        <h3><?php echo $name ?></h3>
        
</div>
<dd><em>Versão <?php echo $version ?></em></dd>
</div>
<div id="menu">

                <?php echo $this->navigation()->menu();?>
<div class="float-right" style="margin-right:10px;">
    <a  id="_logout"  class="btn btn-danger" href="
<?php 
echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'module' => 'default'), '', true); 
?>">Sair<i class='fa fa-sign-out-alt'></i></a>
</div>
    </div>
<br><br>
<div id="newBody" class="clearfix"><!-- /newbody -->
<div id="barra_navegar">
<?php 
echo "Você está aqui: ".$this->navigation()->breadcrumbs()->setSeparator(' &#9654;' . PHP_EOL);
?><!-- /barra navegar -->

</div><!-- /barra navegar -->

<?php 
echo $this->layout()->content 
?>

</div><!-- /newbody -->

</div><!-- /body1 -->

</div><!-- /max -->
<div id="rodape" class='col-md-12 alert alert-secondary'>&copy; Defensoria Pública do Estado do RS</div>

</body>
</html>
